[package]
name = "manas_server_single_fs_noauth"
version = "0.1.0"
edition = "2021"
description = "This binary crate provides a solid server with fs backend, without authentication requirements."
repository = "https://github.com/manomayam/manas"
license = "MIT OR Apache-2.0"

[dependencies]
manas_server = { version = "0.1.0", path = "../..", features = ["backend-fs"] }
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread"] }


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]
