[package]
name = "manas_server_single_s3_wac"
version = "0.1.0"
edition = "2021"
description = "This binary crate provides a solid server with s3 backend, with wac access control."
repository = "https://github.com/manomayam/manas"
license = "MIT OR Apache-2.0"

[dependencies]
manas_server = { version = "0.1.0", path = "../..", features = ["backend-s3", "pdp-wac"] }
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread"] }


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]
